In [ ]:
pip install pygad 

     |████████████████████████████████| 53 kB 946 kB/s 


In [ ]:
import pygad
import numpy as np
import scipy

In [ ]:
X= np.array([[1,0,0,0]]).T
Y = np.array([[0,1,0,0],[0,0,1,0],[0,0,1,0],[0,0,0,1]]).T

In [ ]:
def softmax(x): 
    return np.exp(x)/sum(np.exp(x))

In [ ]:
def crossEntropy(X,Y):
    return -np.sum(np.log(X)*Y)

In [ ]:
def GA_RNN(solution, solution_idx):
    Wxh = solution[0:12].reshape(3,4)
    Whh = solution[12:21].reshape(3,3)
    Why = solution[21:33].reshape(4,3)
    bh = solution[33:36].reshape(3,1)
    by = solution[36:].reshape(4,1)
    hs = np.zeros((4,1))
    xs = np.zeros((4,4))
    h_s = np.zeros((3,1))
    ys = X
    # ps = np.zeros((4,1))

    for t in range(4):
        xs = ys[:,-1].reshape(4,1)# encode in 1-of-k representation
        
        h_t = np.tanh(np.dot(Wxh, xs) + np.dot(Whh, h_s[:,-1].reshape(3,1) )+ bh) # hidden state
        h_s = np.hstack((h_s,h_t))    
        y_t = softmax(np.dot(Why, h_t) + by) # unnormalized log probabilities for next chars
        ys = np.hstack((ys,y_t))

    h_s = h_s[:,1:]
    ys = ys[:,1:]
    return 1/np.sum(crossEntropy(ys,Y))

In [ ]:
fitness_function = GA_RNN
num_generations = 100
num_parents_mating = 10
sol_per_pop = 20
num_genes = 40

init_range_low = -2
init_range_high = 5

parent_selection_type = "sss"
keep_parents = 1

crossover_type ="single_point"

mutation_type = "random"
mutation_percent_genes = 20


ga_instance = pygad.GA(
                       num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       init_range_low=init_range_low,
                       init_range_high=init_range_high,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes)

ga_instance.run()

solution, solution_fitness, solution_idx = ga_instance.best_solution()

print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))




Fitness value of the best solution = 69346957.75547665


In [ ]:
def RNN(solution, solution_idx,X,Y):
    Wxh = solution[0:12].reshape(3,4)
    Whh = solution[12:21].reshape(3,3)
    Why = solution[21:33].reshape(4,3)
    bh = solution[33:36].reshape(3,1)
    by = solution[36:].reshape(4,1)
    hs = np.zeros((4,1))
   
    Loss =0
    xs = np.zeros((4,4))
    h_s = np.zeros((3,1))
    ys = X
    # ps = np.zeros((4,1))

    for t in range(X.shape[0]):
        xs = ys[:,-1].reshape(4,1) # encode in 1-of-k representation
        
        h_t = np.tanh(np.dot(Wxh, xs) + np.dot(Whh, h_s[:,-1].reshape(3,1) )+ bh) # hidden state
        h_s = np.hstack((h_s,h_t))    
        y_t = softmax(np.dot(Why, h_t) + by) # unnormalized log probabilities for next chars
        ys = np.hstack((ys,y_t))

    h_s = h_s[:,1:]
    ys = ys[:,1:]
    return h_s,ys,crossEntropy(ys,Y)

In [ ]:
h,y,Loss =RNN(solution,solution,X,Y)
print("Ket qua thu duoc y = \n {} \n Ket qua sau khi lam tron 3 chu so y= \n {}. \n Loss= {} ".format(y,np.round(y,decimals=3),Loss))


Ket qua thu duoc y = 
 [[1.90394660e-09 2.41133510e-10 9.18509901e-13 1.63894646e-10]
 [9.99999994e-01 5.05733280e-09 3.63853720e-15 3.43758762e-09]
 [8.52224696e-10 9.99999995e-01 1.00000000e+00 1.61672353e-12]
 [2.76000088e-09 4.30071339e-15 1.57930505e-12 9.99999996e-01]] 
 Ket qua sau khi lam tron 3 chu so y= 
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]]. 
 Loss= 1.4420243257477655e-08 


In [ ]:
Wxh = solution[0:12].reshape(3,4)
Whh = solution[12:21].reshape(3,3)
Why = solution[21:33].reshape(4,3)
bh = solution[33:36].reshape(3,1)
by = solution[36:].reshape(4,1)

In [ ]:
print("Wxh:\n {} ".format(np.round(Wxh,decimals=3)))
print("Whh:\n {} ".format(np.round(Whh,decimals=3)))
print("Why:\n {} ".format(np.round(Why,decimals=3)))
print("bh:\n {} ".format(np.round(bh,decimals=3)))
print("by:\n {} ".format(np.round(by,decimals=3)))

Wxh:
 [[ 3.799  1.785 -3.698 -2.854]
 [-3.972  0.693  6.463 -4.443]
 [ 3.15  -2.258  4.773  6.607]] 
Whh:
 [[ 0.353  4.72   2.275]
 [-6.346  3.884 -0.824]
 [-3.105  4.441  0.048]] 
Why:
 [[  0.48    5.263  -0.816]
 [  5.326   1.584   7.231]
 [ -2.817   0.068 -11.979]
 [ -5.769  10.089   5.475]] 
bh:
 [[ 1.412]
 [-0.759]
 [ 0.015]] 
by:
 [[-1.488]
 [ 2.049]
 [ 6.933]
 [ 3.689]] 


In [ ]:
data ='Helo'
# define a mapping of chars to integers
char_to_int =  {'H':0,'e':1,'l':2,"o":3}
int_to_char = {0:'H',1:'e',2:'l',3:"o"}
# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)
# # one hot encode
onehot_encoded = list()
for value in integer_encoded:
	letter = [0 for _ in range(len(data))]
	letter[value] = 1
	onehot_encoded.append(letter)
print(np.array(onehot_encoded).T)

[0, 1, 2, 3]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
